Repository ossmini/Kakao_I_OpenBuilder_Library, pull requests merged in 2022-05, with the labels that each got.

#70 feat: SkillTemplate - Profile 구현 [ossmini#68]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Profile.java
Labels: feature

#71 feat: SkillTemplate - Link 구현 [ossmini#69]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Link.java
Labels: feature

#76 chore: common 경로의 클래스들을 coverage 측정 대상에서 제외
  pom.xml
Labels: chore

#73 feat: SkillTemplate - Button 구현 [ossmini#65]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Button.java
Labels: feature

#74 feat: SkillTemplate - Forwardable 구현 [ossmini#66]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Forwardable.java
Labels: feature

#77 chore: 잘못된 Convention 수정
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Button.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Forwardable.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Link.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Profile.java
Labels: chore

#72 feat: SkillTemplate - Thumbnail 구현 [ossmini#64]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Thumbnail.java
Labels: feature

#75 feat: SkillTemplate - CarouselHeader 구현 [ossmini#67]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/CarouselHeader.java
Labels: feature

#79 fix: SonarCloud에서 Coverage가 잘못 측정되는 오류 수정 [#78]
  .github/workflows/sonar.yml
Labels: fix

#63 feat: SkillTemplate - SimpleImage 구현 [#55]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/Component.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/SimpleImage.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/SimpleText.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/TemplateBuilder.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponseTest.java
  testResources/skill_response_simple_image.json
  testResources/skill_response_simple_text.json
Labels: feature
