Repository ossmini/Kakao_I_OpenBuilder_Library, pull requests merged in 2022-06, with the labels that each got.

#82 docs: README.md 수정 [ossmini#27]
  README.md
Labels: docs

#85 feat: SkillResponse - Basic Card 구현 [#56]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Button.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Thumbnail.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/BasicCard.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/Component.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/TemplateBuilder.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponseTest.java
  testResources/skill_response_basic_card.json
Labels: feature

#86 chore: project organization 이름 변경
  pom.xml
Labels: chore

#87 release: v1.0.2 배포
  .github/workflows/sonar.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  pom.xml
  src/main/java/dev/mini/kakaoiopenbuilder/skill/Main.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/exception/ComponentsOutOfBoundsException.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayload.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/Action.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/DetailParams.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/bot/Bot.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Extra.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Intent.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Knowledge.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/MatchedKnowledges.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Reason.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Block.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Params.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Properties.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/User.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/UserRequest.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SKillResponseBuilder.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillData.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataBuilder.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponse.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Button.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/CarouselHeader.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Forwardable.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Link.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Profile.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/common/Thumbnail.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/BasicCard.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/Component.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/SimpleImage.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/SimpleText.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/context/ContextControl.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/Output.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/Template.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/TemplateBuilder.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayloadTest.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataTest.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponseTest.java
  testResources/skill_response_basic_card.json
  testResources/skill_response_simple_image.json
  testResources/skill_response_simple_text.json
Labels: feature, fix

#89 docs: README.md 수정 [ossmini#88]
  README.md
Labels: docs

#91 docs: README.md 수정 [ossmini#90]
  README.md
Labels: docs
