Repository ossmini/Kakao_I_OpenBuilder_Library, pull requests merged in 2022-04, with the labels that each got.

#1 init: 프로젝트 초기화 및 패키지 배포 설정
  .github/workflows/publish.yml
  .gitignore
  pom.xml
Labels: enhancement

#8 feat: SonarCloud를 통한 코드 정적 분석 [#7]
  .github/workflows/build.yml
  pom.xml
Labels: infra

#10 fix: SonarCloud가 브랜치에서 동작하지 않음 [#9]
  .github/workflows/build.yml
  pom.xml
Labels: fix

#17 fix: Github Action이 동작하지 않는 오류 수정 [#16]
  .github/workflows/build.yml
  .github/workflows/sonar.yml
Labels: fix

#18 Revert "fix: Github Action이 동작하지 않는 오류 수정 [#16]"
  .github/workflows/build.yml
  .github/workflows/sonar.yml
Labels: fix

#19 fix: Github Action이 동작하지 않는 오류 수정 [#16]
  .github/workflows/build.yml
  .github/workflows/sonar.yml
Labels: fix

#15 feat: SkillPayload - userRequest 구현 [#12]
  pom.xml
  src/main/java/dev/mini/skill/Main.java
  src/main/java/dev/mini/skill/payload/SkillPayload.java
  src/main/java/dev/mini/skill/payload/userrequest/Block.java
  src/main/java/dev/mini/skill/payload/userrequest/Params.java
  src/main/java/dev/mini/skill/payload/userrequest/Properties.java
  src/main/java/dev/mini/skill/payload/userrequest/User.java
  src/main/java/dev/mini/skill/payload/userrequest/UserRequest.java
  src/test/java/dev/mini/skill/payload/SkillPayloadTest.java
  testResources/skill_payload.json
Labels: feature

#21 fix: Github Actions와 SonarCloud 연동 오류 [#20]
  .github/workflows/build.yml
  .github/workflows/sonar.yml
Labels: fix

#22 feat: SkillPayload - bot 구현
  src/main/java/dev/mini/skill/payload/SkillPayload.java
  src/main/java/dev/mini/skill/payload/bot/Bot.java
  src/test/java/dev/mini/skill/payload/SkillPayloadTest.java
Labels: feature

#24 refactor: SkillPayload test code refactor
  src/test/java/dev/mini/skill/payload/SkillPayloadTest.java
Labels: refactor

#26 feat: SkillPayload - intent 구현 [#11]
  src/main/java/dev/mini/skill/payload/SkillPayload.java
  src/main/java/dev/mini/skill/payload/intent/Extra.java
  src/main/java/dev/mini/skill/payload/intent/Intent.java
  src/main/java/dev/mini/skill/payload/intent/Knowledge.java
  src/main/java/dev/mini/skill/payload/intent/MatchedKnowledges.java
  src/main/java/dev/mini/skill/payload/intent/Reason.java
  src/test/java/dev/mini/skill/payload/SkillPayloadTest.java
Labels: feature

#29 feat: SkillPayload - action 구현 [#14]
  src/main/java/dev/mini/skill/payload/SkillPayload.java
  src/main/java/dev/mini/skill/payload/action/Action.java
  src/main/java/dev/mini/skill/payload/action/DetailParams.java
  src/test/java/dev/mini/skill/payload/SkillPayloadTest.java
  testResources/skill_payload.json
Labels: feature

#30 chore: 실행 가능한 JAR파일 생성 [#25]
  pom.xml
  src/main/java/dev/mini/kakaoiopenbuilder/skill/Main.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayload.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/Action.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/DetailParams.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/bot/Bot.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Extra.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Intent.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Knowledge.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/MatchedKnowledges.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Reason.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Block.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Params.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Properties.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/User.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/UserRequest.java
  src/main/java/dev/mini/skill/Main.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayloadTest.java
Labels: feature

#33 feat: 시스템 엔티티(@sys.*) 구현 [#32]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/util/SystemEntity.java
Labels: feature

#40 feat: SkillResponse - SkillData 구현
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillData.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataBuilder.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponse.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataTest.java
  testResources/skill_response_data.json
Labels: feature

#36 docs: 이슈, PR 템플릿 작성 [#3]
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#35 docs: pom.xml 프로젝트 정보 설정 [#31]
  pom.xml
Labels: docs

#34 docs: Apache 2.0 라이센스 선정 [#28]
  LICENSE
Labels: docs

#37 release: v1.0.0 배포
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/sonar.yml
  .gitignore
  LICENSE
  pom.xml
  src/main/java/dev/mini/kakaoiopenbuilder/skill/Main.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayload.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/Action.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/DetailParams.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/bot/Bot.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Extra.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Intent.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Knowledge.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/MatchedKnowledges.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Reason.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Block.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Params.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Properties.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/User.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/UserRequest.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillData.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataBuilder.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponse.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/util/SystemEntity.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayloadTest.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataTest.java
  testResources/skill_payload.json
  testResources/skill_response_data.json
Labels: feature

#42 feat: release draft 자동 생성 설정
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: infra

#44 release: v1.0.0 배포
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter-config.yml
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/sonar.yml
  .gitignore
  LICENSE
  pom.xml
  src/main/java/dev/mini/kakaoiopenbuilder/skill/Main.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayload.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/Action.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/DetailParams.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/bot/Bot.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Extra.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Intent.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Knowledge.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/MatchedKnowledges.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Reason.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Block.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Params.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Properties.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/User.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/UserRequest.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillData.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataBuilder.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponse.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/util/SystemEntity.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayloadTest.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataTest.java
  testResources/skill_payload.json
  testResources/skill_response_data.json
Labels: feature

#46 fix: pom.xml version 변경 [#45]
  pom.xml
Labels: fix

#50 feat: SkillResponse Builder 구현 및 리펙터링
  src/main/java/dev/mini/kakaoiopenbuilder/skill/Main.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SKillResponseBuilder.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillData.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataBuilder.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponse.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/context/ContextControl.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/Template.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataTest.java
Labels: feature, refactor

#51 feat: SkillTemplate - SimpleText 구현 [#49]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponse.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/Component.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/SimpleText.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/Output.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/Template.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/TemplateBuilder.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponseTest.java
  testResources/skill_response_simple_text.json
Labels: feature

#52 refactor: equals and hashcode 삭제
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayload.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/Action.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/action/DetailParams.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/bot/Bot.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Extra.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Intent.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Knowledge.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/MatchedKnowledges.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/intent/Reason.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Block.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Params.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/Properties.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/User.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/payload/userrequest/UserRequest.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponse.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/component/SimpleText.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/Template.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayloadTest.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillDataTest.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponseTest.java
Labels: refactor

#53 feat: JaCoCo를 이용한 Code Coverage 측정 [#23]
  pom.xml
  src/test/java/dev/mini/kakaoiopenbuilder/skill/payload/SkillPayloadTest.java
Labels: infra

#54 chore: sonar qube에서 감지된 code smell 제거
  src/main/java/dev/mini/kakaoiopenbuilder/skill/Main.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/SKillResponseBuilder.java
Labels: chore

#61 feat: 출력할 수 있는 스킬 컴포넌트의 개수 제한 [#49]
  src/main/java/dev/mini/kakaoiopenbuilder/skill/exception/ComponentsOutOfBoundsException.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/TemplateBuilder.java
  src/test/java/dev/mini/kakaoiopenbuilder/skill/response/SkillResponseTest.java
Labels: feature

#62 refactor: SonarQube에서 감지된 Code Smell 제거
  src/main/java/dev/mini/kakaoiopenbuilder/skill/exception/ComponentsOutOfBoundsException.java
  src/main/java/dev/mini/kakaoiopenbuilder/skill/response/template/TemplateBuilder.java
Labels: refactor
